<p style="color:#FFF; background-color:#00C; padding:12px; font-size:20px; text-align:center">
<span style="font-size:48px"><b>PACKAGE : NUMPY</b></span><br>
<span style="width:49%; display:inline-block; text-align:left">Christophe Schlick</span>
<span style="width:49%; display:inline-block; text-align:right"><i>schlick@u-bordeaux.fr</i></span></p>

Le package [**numpy**](https://numpy.readthedocs.io/en/latest) fournit à Python des outils flexibles et efficaces pour le stockage et le traitement de données numériques, pour un nombre quelconque de dimensions

La documentation complète du package se trouve sur le site [**ReadTheDocs**](https://numpy.readthedocs.io) mais elle est également directement disponible dans le menu `Help` de l'interface Jupyter. Ce notebook a pour objet de faire un tour d'horizon rapide et de montrer les fonctionnalités les plus utiles de **numpy** dans le cadre d'une utilisation au sein de l'environnement Jupyter
    
---
On importe habituellement le package **numpy** par le biais d'un alias, avec la commande suivante :

> `import numpy as np`

afin de racourcir le préfixe qu'il faudra utiliser pour accéder aux fonctions qu'il contient :

In [1]:
import numpy as np # import du package 'numpy' avec alias 'np'
from SRC.show import show # import de la fonction 'show' permettant de simplifier certaines explications

<h2 style="padding:16px; color:#FFF; background-color:#00C">A - Création de tables</h2>

### 1 - Création de tables à partir de listes Python

In [2]:
a = np.array([1,-2,3,-4,-5,6,-7,8]) # création d'une table 1D à partir d'une liste standard

In [3]:
a # numpy fournit un nouveau type de données appelé 'array'

array([ 1, -2,  3, -4, -5,  6, -7,  8])

In [4]:
print(a) # affichage plus compact et plus lisible

[ 1 -2  3 -4 -5  6 -7  8]


In [5]:
show("a; a.shape; a.size; a.ndim; a.dtype; a.itemsize; a.nbytes") # propriétés de la table

a = [ 1 -2  3 -4 -5  6 -7  8]
a.shape = (8,)
a.size = 8
a.ndim = 1
a.dtype = int32
a.itemsize = 4
a.nbytes = 32


In [6]:
a = np.array([1,-2,3,-4,-5,6,-7,8], dtype=float) # création d'une table 1D en forçant le type de données
show("a; a.shape; a.size; a.ndim; a.dtype; a.itemsize; a.nbytes") # propriétés de la table

a = [ 1. -2.  3. -4. -5.  6. -7.  8.]
a.shape = (8,)
a.size = 8
a.ndim = 1
a.dtype = float64
a.itemsize = 8
a.nbytes = 64


In [7]:
a = np.array([[1,-2,3,-4], [-5,6,-7,8]]) # création d'une table 2D à partir d'une liste de listes
show("a#; a.shape; a.size; a.ndim; a.dtype; a.itemsize; a.nbytes") # propriétés de la table

a =
[[ 1 -2  3 -4]
 [-5  6 -7  8]]
a.shape = (2, 4)
a.size = 8
a.ndim = 2
a.dtype = int32
a.itemsize = 4
a.nbytes = 32


---
### 2 - Création de tables à l'aide de méthodes **numpy** spécifiques

In [8]:
print(np.zeros((3,5))) # création d'une table initialisée à 0 (type 'float' par défaut)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
print(np.zeros((3,5), dtype=int)) # idem en forçant le type à 'int'

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [10]:
print(np.ones((2,3,8))) # création d'une table initialisée à 1

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [11]:
print(np.full((2,3,8), 'x')) # création d'une table initialisée à une valeur donnée

[[['x' 'x' 'x' 'x' 'x' 'x' 'x' 'x']
  ['x' 'x' 'x' 'x' 'x' 'x' 'x' 'x']
  ['x' 'x' 'x' 'x' 'x' 'x' 'x' 'x']]

 [['x' 'x' 'x' 'x' 'x' 'x' 'x' 'x']
  ['x' 'x' 'x' 'x' 'x' 'x' 'x' 'x']
  ['x' 'x' 'x' 'x' 'x' 'x' 'x' 'x']]]


In [12]:
print(np.eye(3)) # création d'une matrice identité

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
print(np.tri(5)) # création d'une matrice triangulaire sur base carrée

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


In [14]:
print(np.tri(6,9,2)) # création d'une matrice triangulaire sur base rectangle avec décalage de diagonale

[[1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0.]]


In [15]:
print(np.arange(99,0,-11)) # création d'une table à partir d'un itérateur à pas entiers

[99 88 77 66 55 44 33 22 11]


In [16]:
print(np.linspace(0,1,11)) # idem avec un itérateur à pas linéaires

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [17]:
print(np.logspace(-4,4,9)) # idem avec un itérateur à pas logarithmiques

[1.e-04 1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]


In [18]:
print(np.random.rand(4,6)) # création d'une table de valeurs aléatoires, distribution uniforme sur [0,1)

[[0.25271358 0.93638225 0.80308652 0.73345568 0.31889539 0.71988915]
 [0.47514706 0.22160636 0.50224442 0.63139119 0.83118207 0.32098757]
 [0.11109195 0.20386571 0.03326375 0.79510133 0.97894854 0.50126112]
 [0.49772415 0.12414954 0.80254524 0.3969369  0.76722923 0.68386739]]


In [19]:
print(np.random.normal(0, 1, (4,6))) # idem avec distribution normale (moyenne = 0, écart-type = 1)

[[-0.24646394 -0.54695529 -1.63254444  0.43361308 -0.19518488 -0.24002785]
 [-1.20846475  1.5124128   1.43449707 -0.78647672 -1.27792905  1.27133739]
 [ 0.36601339 -1.96070059 -1.01193099  0.64305867  1.08872612 -0.00731036]
 [-0.33048762 -1.14335824  0.19176192  0.19645133  0.93727738  2.08260615]]


In [20]:
print(np.random.randint(1, 7, (5,30))) # idem avec des valeurs aléatoires entières sur {1..6}

[[2 2 3 4 4 1 6 2 4 6 4 4 4 6 4 2 4 5 4 6 1 5 5 2 3 2 2 1 1 1]
 [6 6 3 6 4 2 4 1 6 3 4 2 3 1 2 5 3 4 3 5 2 2 4 4 5 4 1 5 1 5]
 [1 5 2 2 3 3 6 5 4 4 2 1 3 1 1 5 1 2 5 1 3 6 5 1 6 3 4 4 4 5]
 [1 4 4 2 5 4 6 5 5 3 5 3 1 2 5 2 3 5 4 3 1 2 6 1 2 3 1 2 2 4]
 [4 5 3 4 5 3 6 5 4 1 1 2 6 5 2 2 5 3 2 3 4 3 1 6 3 2 5 1 3 4]]


<h2 style="padding:16px; color:#FFF; background-color:#00C">B - Transformation de tables</h2>

### 1 - Modification de forme ou de dimension

In [21]:
a = np.array([[1,-2,3,-4], [-5,6,-7,8]])
print(a)

[[ 1 -2  3 -4]
 [-5  6 -7  8]]


In [22]:
print(a.T) # transposition de la table (= inversion de l'ordre des dimensions)

[[ 1 -5]
 [-2  6]
 [ 3 -7]
 [-4  8]]


In [23]:
print(a.ravel()) # aplatissement de la table (= conversion en table 1D)

[ 1 -2  3 -4 -5  6 -7  8]


In [24]:
print(a.T.ravel()) # idem avec inversion de l'ordre des dimensions

[ 1 -5 -2  6  3 -7 -4  8]


In [25]:
print(a.reshape((1,8))) # modification de la forme d'une table existante (1 ligne, 8 colonnes)

[[ 1 -2  3 -4 -5  6 -7  8]]


In [26]:
print(a.reshape((8,1))) # idem (8 lignes, 1 colonne)

[[ 1]
 [-2]
 [ 3]
 [-4]
 [-5]
 [ 6]
 [-7]
 [ 8]]


In [27]:
print(a.reshape((4,2))) # idem (4 lignes, 2 colonnes)

[[ 1 -2]
 [ 3 -4]
 [-5  6]
 [-7  8]]


In [28]:
print(a.reshape((2,2,2))) # idem (2 lignes, 2 colonnes, 2 plans)

[[[ 1 -2]
  [ 3 -4]]

 [[-5  6]
  [-7  8]]]


In [29]:
print(a[None, ...]) # ajout d'une dimension en tête

[[[ 1 -2  3 -4]
  [-5  6 -7  8]]]


In [30]:
print(a[:, None, :]) # ajout d'une dimension au centre

[[[ 1 -2  3 -4]]

 [[-5  6 -7  8]]]


In [31]:
print(a[..., None]) # ajout d'une dimension en queue

[[[ 1]
  [-2]
  [ 3]
  [-4]]

 [[-5]
  [ 6]
  [-7]
  [ 8]]]


---
### 2 - Transformations particulières pour table 2D

In [32]:
print(np.fliplr(a)) # transposition left <-> right

[[-4  3 -2  1]
 [ 8 -7  6 -5]]


In [33]:
print(np.flipud(a)) # transposition up <-> down

[[-5  6 -7  8]
 [ 1 -2  3 -4]]


In [34]:
print(np.rot90(a)) # rotation 90° (sens trigonométrique)

[[-4  8]
 [ 3 -7]
 [-2  6]
 [ 1 -5]]


In [35]:
print(np.rot90(a,2)) # rotation 180°

[[ 8 -7  6 -5]
 [-4  3 -2  1]]


In [36]:
print(np.rot90(a,3)) # rotation 270°

[[-5  1]
 [ 6 -2]
 [-7  3]
 [ 8 -4]]


---
### 3 - Fusion et séparation de tables

In [37]:
print(np.vstack([a,-a,a])) # fusion en hauteur (vertical)

[[ 1 -2  3 -4]
 [-5  6 -7  8]
 [-1  2 -3  4]
 [ 5 -6  7 -8]
 [ 1 -2  3 -4]
 [-5  6 -7  8]]


In [38]:
print(np.hstack([a,-a,a])) # fusion en largeur (horizontal)

[[ 1 -2  3 -4 -1  2 -3  4  1 -2  3 -4]
 [-5  6 -7  8  5 -6  7 -8 -5  6 -7  8]]


In [39]:
print(np.array([a,-a,a])) # fusion en profondeur

[[[ 1 -2  3 -4]
  [-5  6 -7  8]]

 [[-1  2 -3  4]
  [ 5 -6  7 -8]]

 [[ 1 -2  3 -4]
  [-5  6 -7  8]]]


In [40]:
print(np.dstack([a,-a,a])) # fusion par position d'élément

[[[ 1 -1  1]
  [-2  2 -2]
  [ 3 -3  3]
  [-4  4 -4]]

 [[-5  5 -5]
  [ 6 -6  6]
  [-7  7 -7]
  [ 8 -8  8]]]


In [41]:
b = np.vstack([a,-a,a]); c, d = np.vsplit(b, 2) # séparation verticale (équitable)
show("b#; c#; d#")

b =
[[ 1 -2  3 -4]
 [-5  6 -7  8]
 [-1  2 -3  4]
 [ 5 -6  7 -8]
 [ 1 -2  3 -4]
 [-5  6 -7  8]]
c =
[[ 1 -2  3 -4]
 [-5  6 -7  8]
 [-1  2 -3  4]]
d =
[[ 5 -6  7 -8]
 [ 1 -2  3 -4]
 [-5  6 -7  8]]


In [42]:
b = np.hstack([a,-a,a]); c, d = np.hsplit(b, [3]) # séparation horizontale (ajustable)
show("b#; c#; d#")

b =
[[ 1 -2  3 -4 -1  2 -3  4  1 -2  3 -4]
 [-5  6 -7  8  5 -6  7 -8 -5  6 -7  8]]
c =
[[ 1 -2  3]
 [-5  6 -7]]
d =
[[-4 -1  2 -3  4  1 -2  3 -4]
 [ 8  5 -6  7 -8 -5  6 -7  8]]


<h2 style="padding:16px; color:#FFF; background-color:#00C">C - Accès aux éléments d'une table</h2>

### 1 - Accès aux éléments par indices, tranches et tuples

In [43]:
a = np.array([[1,-2,3,-4], [-5,6,-7,8]])

In [44]:
show("a#;; a[0,0]; a[0,1]; a[1,0]; a[-1,-1];; a[1,:]; a[:,1];")
show("a[0:2,1:3]#;; a[:,(3,1,2,0)]#;; a[:,(3,1,2,0)]#;; a[(0,1,0),:3]#;")

a =
[[ 1 -2  3 -4]
 [-5  6 -7  8]]

a[0,0] = 1
a[0,1] = -2
a[1,0] = -5
a[-1,-1] = 8

a[1,:] = [-5  6 -7  8]
a[:,1] = [-2  6]

a[0:2,1:3] =
[[-2  3]
 [ 6 -7]]

a[:,(3,1,2,0)] =
[[-4 -2  3  1]
 [ 8  6 -7 -5]]

a[:,(3,1,2,0)] =
[[-4 -2  3  1]
 [ 8  6 -7 -5]]

a[(0,1,0),:3] =
[[ 1 -2  3]
 [-5  6 -7]
 [ 1 -2  3]]



---
### 2 - Accès aux éléments par prédicats et méthodes

In [45]:
show("a[a>0]; a[abs(a)>4]; a[(a>0) & (a<4)]; a[(a%2 == 0) | (a%3 == 0)]")

a[a>0] = [1 3 6 8]
a[abs(a)>4] = [-5  6 -7  8]
a[(a>0) & (a<4)] = [1 3]
a[(a%2 == 0) | (a%3 == 0)] = [-2  3 -4  6  8]


In [46]:
a[a > 0] = 0
print(a)

[[ 0 -2  0 -4]
 [-5  0 -7  0]]


---
### 3 - Itération sur les éléments

In [47]:
for index, value in np.ndenumerate(a): print(f"index = {index}  value = {value}")

index = (0, 0)  value = 0
index = (0, 1)  value = -2
index = (0, 2)  value = 0
index = (0, 3)  value = -4
index = (1, 0)  value = -5
index = (1, 1)  value = 0
index = (1, 2)  value = -7
index = (1, 3)  value = 0


<h2 style="padding:16px; color:#FFF; background-color:#00C">D - Opérations sur les tables</h2>

### 1 - Manipulation par opérateurs

In [65]:
a = np.array([[1,-2,3,-4], [-5,6,-7,8]]); print(a)

[[ 1 -2  3 -4]
 [-5  6 -7  8]]


In [66]:
print(1 + 2 * a) # combinaison linéaire avec broadcasting

[[  3  -3   7  -7]
 [ -9  13 -13  17]]


In [67]:
print(a * a) # produit interne (élément par élément)

[[ 1  4  9 16]
 [25 36 49 64]]


In [68]:
print(np.outer(a, a)) # produit externe (élément par élément sur table aplatie)

[[  1  -2   3  -4  -5   6  -7   8]
 [ -2   4  -6   8  10 -12  14 -16]
 [  3  -6   9 -12 -15  18 -21  24]
 [ -4   8 -12  16  20 -24  28 -32]
 [ -5  10 -15  20  25 -30  35 -40]
 [  6 -12  18 -24 -30  36 -42  48]
 [ -7  14 -21  28  35 -42  49 -56]
 [  8 -16  24 -32 -40  48 -56  64]]


In [69]:
print(a @ a.T) # produit matriciel (transposée à droite)

[[ 30 -70]
 [-70 174]]


In [70]:
print(a.T @ a) # produit matriciel (transposée à gauche)

[[ 26 -32  38 -44]
 [-32  40 -48  56]
 [ 38 -48  58 -68]
 [-44  56 -68  80]]


---
### 2 - Manipulation par fonctions

In [71]:
', '.join(f for f in dir(np) if f[0] != '_')

'ALLOW_THREADS, AxisError, BUFSIZE, Bytes0, CLIP, ComplexWarning, DataSource, Datetime64, ERR_CALL, ERR_DEFAULT, ERR_IGNORE, ERR_LOG, ERR_PRINT, ERR_RAISE, ERR_WARN, FLOATING_POINT_SUPPORT, FPE_DIVIDEBYZERO, FPE_INVALID, FPE_OVERFLOW, FPE_UNDERFLOW, False_, Inf, Infinity, MAXDIMS, MAY_SHARE_BOUNDS, MAY_SHARE_EXACT, MachAr, ModuleDeprecationWarning, NAN, NINF, NZERO, NaN, PINF, PZERO, RAISE, RankWarning, SHIFT_DIVIDEBYZERO, SHIFT_INVALID, SHIFT_OVERFLOW, SHIFT_UNDERFLOW, ScalarType, Str0, Tester, TooHardError, True_, UFUNC_BUFSIZE_DEFAULT, UFUNC_PYVALS_NAME, Uint64, VisibleDeprecationWarning, WRAP, abs, absolute, add, add_docstring, add_newdoc, add_newdoc_ufunc, alen, all, allclose, alltrue, amax, amin, angle, any, append, apply_along_axis, apply_over_axes, arange, arccos, arccosh, arcsin, arcsinh, arctan, arctan2, arctanh, argmax, argmin, argpartition, argsort, argwhere, around, array, array2string, array_equal, array_equiv, array_repr, array_split, array_str, asanyarray, asarray, asar

In [72]:
print(np.abs(a)) # valeur absolue (élément par élément)

# liste de quelques fonctions usuelles :
# +  -  *  /  //  %  **  abs  floor  ceil  round  real  imag  hypot  angle  sqrt  exp  log  log2  log10
# cos  sin  tan  arccos  arcsin  arctan  arctan2  cosh  sinh  tanh  arccosh  arcsinh  arctanh
# sum  prod  mean  average  median  var  std  any  all  nonzero  isfinite  isposinf  isneginf

[[1 2 3 4]
 [5 6 7 8]]


In [73]:
print(np.diag(a)) # extraction de diagonale

[1 6]


In [74]:
print(np.diag(a, 2)) # extraction de diagonale avec décalage

[3 8]


In [75]:
print(np.tril(a)) # extraction du triangle inférieur

[[ 1  0  0  0]
 [-5  6  0  0]]


In [76]:
print(np.triu(a, 2)) # extraction du triangle supérieur avec décalage

[[ 0  0  3 -4]
 [ 0  0  0  8]]


In [101]:
b = np.multiply(a, 2) # équivalent à 'b = a * 2'
show('b#')
np.add.at(b, ((0,1),(1,3)), 10) # opération sur une partie des éléments (indices définis par deux tuples)
show('b#')

b =
[[  2  -4   6  -8]
 [-10  12 -14  16]]
b =
[[  2   6   6  -8]
 [-10  12 -14  26]]


---
### 3 - Manipulation par méthodes

In [102]:
', '.join(f for f in dir(a) if f[0] != '_')

'T, all, any, argmax, argmin, argpartition, argsort, astype, base, byteswap, choose, clip, compress, conj, conjugate, copy, ctypes, cumprod, cumsum, data, diagonal, dot, dtype, dump, dumps, fill, flags, flat, flatten, getfield, imag, item, itemset, itemsize, max, mean, min, nbytes, ndim, newbyteorder, nonzero, partition, prod, ptp, put, ravel, real, repeat, reshape, resize, round, searchsorted, setfield, setflags, shape, size, sort, squeeze, std, strides, sum, swapaxes, take, tobytes, tofile, tolist, tostring, trace, transpose, var, view'

In [122]:
show("a#;;  np.where(a>0, a, 0)#;; np.where(abs(a)>4, a, 0)#;")
show("np.where(a%2 == 0, a, 0)#;;np.where((a>-6) & (a<4), a, 0)#;") # opérateurs booléens possibles : & | ^
show("a.max(); a.max(axis=0); a.min(); a.min(axis=1); a.mean(); a.mean(axis=0);")
show("a.argmax(); a.argmax(axis=0); a.argmin(); a.argmin(axis=1);;")
show("a.sum(axis=0); a.cumsum(axis=1)#;; a.prod(axis=0); a.cumprod(axis=1)#")

# liste de quelques méthodes usuelles : 
# max min argmax argmin sum cumsum prod cumprod mean median var std percentile any all 

a =
[[ 1 -2  3 -4]
 [-5  6 -7  8]]

np.where(a>0, a, 0) =
[[1 0 3 0]
 [0 6 0 8]]

np.where(abs(a)>4, a, 0) =
[[ 0  0  0  0]
 [-5  6 -7  8]]

np.where(a%2 == 0, a, 0) =
[[ 0 -2  0 -4]
 [ 0  6  0  8]]

np.where((a>-6) & (a<4), a, 0) =
[[ 1 -2  3 -4]
 [-5  0  0  0]]

a.max() = 8
a.max(axis=0) = [1 6 3 8]
a.min() = -7
a.min(axis=1) = [-4 -7]
a.mean() = 0.0
a.mean(axis=0) = [-2.  2. -2.  2.]

a.argmax() = 7
a.argmax(axis=0) = [0 1 0 1]
a.argmin() = 6
a.argmin(axis=1) = [3 2]


a.sum(axis=0) = [-4  4 -4  4]
a.cumsum(axis=1) =
[[ 1 -1  2 -2]
 [-5  1 -6  2]]

a.prod(axis=0) = [ -5 -12 -21 -32]
a.cumprod(axis=1) =
[[   1   -2   -6   24]
 [  -5  -30  210 1680]]


<h2 style="padding:16px; color:#FFF; background-color:#00C">E - Divers</h2>